import Head from "next/head";
import Kanban from "@/components/Kanban";

export default function Home() {
  return (
    <>
      <Head>
        <title>Ada Test - Kanban</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Kanban />
      </main>
    </>
  );
}
